### ISSUE TITLE
Error with CLI `tokenize` using `click==8.1.3`

### ISSUE THREAD

**Issue by gsarti** [alvations/sacremoses#130]
Using the following command produces an exception when `click==8.1.3` (latest) is installed. Click version is not univocally pinned in the requirements (>=7), which causes the error. Downgrading to `click==7.0` fixes the error.

```shell
>>> sacremoses -l fr -j4 tokenize < test.txt > test.tok
Traceback (most recent call last):
  File "/path/venv/bin/sacremoses", line 5, in <module>
    from sacremoses.cli import cli
  File "/path/venv/lib/python3.8/site-packages/sacremoses/cli.py", line 54, in <module>
    @cli.resultcallback()
AttributeError: 'Group' object has no attribute 'resultcallback'
```

**Comment by alvations** [comment]
Thank you for reporting the bug! Changed the code accordingly to fit click 8.0 name change in the call back. 

```
pip install -U sacremoses>=0.50
```

Should work with latest `click` now.

**Comment by eddie-scio** [comment]
Just noting that `wandb` avoids `8.0.0` which makes it incompat: https://github.com/wandb/client/blob/master/requirements.txt#L1

**Comment by alecbrick** [comment]
can we do <8.1?

**Comment by alvations** [comment]
Ah tricky let me see if I can work out something.

**Comment by alvations** [comment]
I've fixed the click dependency to 7.1.2. last version before 8.x (for now) but maybe if this click dependency gets a little too pesky and I'll replace it in the long run. 

Hope it works for everyone now.

**Comment by alecbrick** [comment]
i mean, i think the issue here is that when the code was originally `resultcallback`, `click` wasn't restricted to `<8.0.0` - regardless of any changes that are made now, the old version will still have this issue

i think it's perfectly fine to set `click>=8.0.0` and use `result_callback`, and anyone experiencing this issue needs to either bump `sacremoses` or restrict `click` themselves

**Comment by alvations** [comment]
In the long run, seems like getting rid of click is the way to go. 

Meanwhile I think there's no need to fixed click version to anything. It's a simple name-change difference of the callback function that makes click non back-compatible. 

Let me think of something to monkey-patch just that callback function names.

**Comment by alvations** [comment]
I've uploaded a version that supports both click versions 7.x and 8.x. 

```
pip install -U sacremoses>=0.53
```

IMHO, it's a nasty fix so I'll think hard on how to remove click.

**Comment by alvations** [comment]
Let me know if anyone using either version of clicks fails on your end.
